# Generated by Django 5.1.7 on 2025-03-15 19:31

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteHeaderFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_footer_content', wagtail.fields.StreamField([('policy_block', 3), ('social_media_block', 6)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'link text', 'required': False}), 1: ('wagtail.blocks.TextBlock', (), {'label': 'Enter a valid URL', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('url', 1)]], {'required': False}), 3: ('wagtail.blocks.ListBlock', (2,), {}), 4: ('wagtail.blocks.ChoiceBlock', [], {'blank': True, 'choices': [('fas fa-envelope', 'Mail'), ('fa-brands fa-facebook-f', 'Facebook'), ('fa-brands fa-x-twitter', 'Twitter')], 'help_text': 'Choose a Icon', 'null': True}), 5: ('wagtail.blocks.StructBlock', [[('text', 0), ('url', 1), ('icon_class', 4)]], {'required': False}), 6: ('wagtail.blocks.ListBlock', (5,), {})})),
            ],
        ),
        migrations.CreateModel(
            name='RedirectPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('external_link', models.URLField(blank=True, help_text='Links to an external page?', max_length=255, null=True)),
                ('redirect_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_analytics_tag', models.CharField(blank=True, max_length=300)),
                ('excluded_models_in_data_export', models.TextField(blank=True, default='wagtailcore.modellogentry,wagtailcore.pagelogentry,wagtailcore.pagesubscription,admin.logentry,auth.permission,wagtailsearch.indexentry,wagtailcore.referenceindex,wagtailimages.rendition,contenttypes,sessions,wagtailcore.groupcollectionpermission', verbose_name='excluded_models for archive')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
                ('site_favicon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('site_logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
