# Generated by Django 5.1.7 on 2025-03-17 21:59

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_siteheaderfooter_redirectpage_siteconfiguration'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='KhutbahPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='article',
            name='media_content',
            field=wagtail.fields.StreamField([('document', 1), ('text', 2)], blank=True, block_lookup={0: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 1: ('wagtail.blocks.StructBlock', [[('document', 0)]], {}), 2: ('wagtail.blocks.RichTextBlock', (), {})}, verbose_name='Article Media Content'),
        ),
        migrations.AlterField(
            model_name='khutbah',
            name='media_content',
            field=wagtail.fields.StreamField([('audio', 1)], blank=True, block_lookup={0: ('wagtailmedia.blocks.AudioChooserBlock', (), {'help_text': 'Select an audio file from media library', 'required': False}), 1: ('wagtail.blocks.StructBlock', [[('audio_file', 0)]], {})}, verbose_name='Media Content'),
        ),
    ]
