# Generated by Django 5.1.7 on 2025-03-17 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_khutbahpage_alter_article_media_content_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KhutbahPage',
            new_name='KhutbahListingPage',
        ),
    ]
