# Generated by Django 5.1.7 on 2025-03-18 13:37

import django.db.models.deletion
import taggit.managers
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_homepage_mohadarahlistingpage_motarjmahlistingpage_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='QAListingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='QASmallTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('media_content', wagtail.fields.StreamField([('audio', 1), ('video', 4), ('document', 6), ('text', 7)], blank=True, block_lookup={0: ('wagtailmedia.blocks.AudioChooserBlock', (), {'help_text': 'Select an audio file from media library', 'required': False}), 1: ('wagtail.blocks.StructBlock', [[('audio_file', 0)]], {}), 2: ('wagtailmedia.blocks.VideoChooserBlock', (), {'help_text': 'Select a video file from media library', 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'help_text': 'Or provide a URL to an external video', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('video_file', 2), ('video_url', 3)]], {}), 5: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 6: ('wagtail.blocks.StructBlock', [[('document', 5)]], {}), 7: ('wagtail.blocks.RichTextBlock', (), {})}, verbose_name='Media Content')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Publication Date')),
                ('hits', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False, verbose_name='Muhim')),
                ('search_notes', wagtail.fields.RichTextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.location')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name_plural': 'QA Sounds',
            },
        ),
    ]
