# Generated by Django 5.1.7 on 2025-03-18 14:38

import django.db.models.deletion
import taggit.managers
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_articlelistingpage_delete_articlepage'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BooksPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ContactUsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RenameModel(
            old_name='ArticleListingPage',
            new_name='ArticlesPage',
        ),
        migrations.RenameModel(
            old_name='KhutbahListingPage',
            new_name='KhutabPage',
        ),
        migrations.RenameModel(
            old_name='MohadarahListingPage',
            new_name='MohadaratPage',
        ),
        migrations.RenameModel(
            old_name='MotarjmahListingPage',
            new_name='MotarjmatPage',
        ),
        migrations.RenameModel(
            old_name='SharhuListingPage',
            new_name='ShorohatPage',
        ),
        migrations.RenameModel(
            old_name='QAListingPage',
            new_name='SuwalaatPage',
        ),
        migrations.RenameModel(
            old_name='TilawahListingPage',
            new_name='TilawatPage',
        ),
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-start_date']},
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='date',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='hits',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='location',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='media_content',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='search_notes',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='title',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='book',
            name='edition',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publication_year',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.AddField(
            model_name='announcement',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='media_content',
            field=wagtail.fields.StreamField([('document', 1)], blank=True, block_lookup={0: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 1: ('wagtail.blocks.StructBlock', [[('document', 0)]], {})}, verbose_name='Book Content'),
        ),
        migrations.AlterField(
            model_name='mohadarah',
            name='media_content',
            field=wagtail.fields.StreamField([('audio', 1)], blank=True, block_lookup={0: ('wagtailmedia.blocks.AudioChooserBlock', (), {'help_text': 'Select an audio file from media library', 'required': False}), 1: ('wagtail.blocks.StructBlock', [[('audio_file', 0)]], {})}, verbose_name='Media Content'),
        ),
        migrations.AlterField(
            model_name='motarjmah',
            name='media_content',
            field=wagtail.fields.StreamField([('audio', 1)], blank=True, block_lookup={0: ('wagtailmedia.blocks.AudioChooserBlock', (), {'help_text': 'Select an audio file from media library', 'required': False}), 1: ('wagtail.blocks.StructBlock', [[('audio_file', 0)]], {})}, verbose_name='Media Content'),
        ),
        migrations.AlterField(
            model_name='sharhu',
            name='media_content',
            field=wagtail.fields.StreamField([('audio', 1)], blank=True, block_lookup={0: ('wagtailmedia.blocks.AudioChooserBlock', (), {'help_text': 'Select an audio file from media library', 'required': False}), 1: ('wagtail.blocks.StructBlock', [[('audio_file', 0)]], {})}, verbose_name='Media Content'),
        ),
        migrations.CreateModel(
            name='QATrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField(blank=True, null=True, verbose_name='Publication Date')),
                ('hits', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False, verbose_name='Muhim')),
                ('search_notes', wagtail.fields.RichTextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_content', wagtail.fields.StreamField([('audio', 1)], blank=True, block_lookup={0: ('wagtailmedia.blocks.AudioChooserBlock', (), {'help_text': 'Select an audio file from media library', 'required': False}), 1: ('wagtail.blocks.StructBlock', [[('audio_file', 0)]], {})}, verbose_name='Media Content')),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.location')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name_plural': 'QA Tracks',
            },
        ),
        migrations.DeleteModel(
            name='QASmallTrack',
        ),
    ]
