# Generated by Django 5.1.7 on 2025-03-18 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_announcementspage_bookspage_contactuspage_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Kitab',
        ),
    ]
