from django.core.management.base import BaseCommand
from wagtail.documents.models import Document
from app.models import * 
from wagtail.blocks import StreamBlockValidationError
from wagtail.fields import StreamField
from wagtail import blocks
from wagtailmedia.blocks import AudioChooserBlock, VideoChooserBlock
from wagtailmedia.models import Media

class Command(BaseCommand):
    help = 'Insert audios'

    def add_audios(self, audios, ModelName):
        for title, filename in audios:
            try:
                document = Media.objects.get(file__endswith=filename)
                
                media_content = StreamField([
                    ('audio', blocks.StructBlock([
                        ('audio_file', AudioChooserBlock()),
                    ]))
                ])
                media_content_value = [
                    {
                        'type': 'audio',
                        'value': {
                            'audio_file': document.id,
                        }
                    }
                ]
                
                audio = ModelName(
                    title=title,
                    media_content=media_content_value
                )
                audio.save()
                
                self.stdout.write(self.style.SUCCESS(f"Inserted '{title}' with file '{filename}'"))
            
            except Document.DoesNotExist:
                self.stdout.write(self.style.ERROR(f"Document '{filename}' not found in Wagtail Documents"))
            except StreamBlockValidationError as e:
                self.stdout.write(self.style.ERROR(f"StreamField validation error for '{title}': {e}"))
            except Exception as e:
                self.stdout.write(self.style.ERROR(f"Error inserting '{title}': {e}"))

    def handle(self, *args, **options):


        qa = [
            ('هل يسوغ البحث العلمي للمبتدئ في طلب العلم', 'fawaid_sawthiyah_1.mp3'),
            ('الاعتماد في طلب العلم على الأشرطة', 'fawaid_sawthiyah_2.mp3'),
            ('النصيحة لمن فقد بركة الوقت واستغلاله بالعلم', 'fawaid_sawthiyah_3.mp3'),
            ('مسألة مد الأرجل بعد صلاة الجماعة, أو مقابل الرفوف التي فيها المصاحف والكتب', 'fawaid_sawthiyah_4.mp3'),
            ('موضوع الكلمة: وصايا في طلب العلم (الجزء الأول) ضمن المجلس الثالث من المجالس العلمية الرمضانية بجامع الرضوان عام 1438هـ', 'al_majalis_al_ilmiya_ar_ramadaniyah_1438_sh_bukhary_03.mp3'),
            ('الرد على من يقول: من لم يقبل في الجامعة الإسلامية يترك طلب العلم في المساجد', 'fawaid_sawthiyah_6.mp3'),
            ('كيف الجمع بين طلب العلم وتحصيل الرزق', 'fawaid_sawthiyah_7.mp3'),
            ('كيفية علاج الفتور ودنو الهمة في طلب العلم', 'fawaid_sawthiyah_8.mp3'),
            ('عنوان غير متوفر', 'fawaid_sawthiyah_9.mp3'),
            ('هل خروج السائل من البواسير أثناء الصلاة يبطلها؟', 'fawaid_sawtiyah_sh_albukhary_274.mp3'),
            ('حكم الصلاة خلف الإمام الذي لا يتوضأ من أكل لحم الإبل', 'fawaid_sawtiyah_sh_albukhary_273.mp3'),
            ('نصيحة في أهمية ارتباط طلاب العلم بالعلماء', 'fawaid_sawtiyah_sh_albukhary_272.mp3'),
            ('سبب ذم السلف لمن لم يرحل في طلب الحديث', 'fawaid_sawtiyah_sh_albukhary_271.mp3'),
            ('حكم الاجتماع لمدارسة العلم وعدم الخروج لصلاة الجماعة خوفا من سلطات الأمن', 'fawaid_sawtiyah_sh_albukhary_270.mp3'),
            ('«الكذاب» جرح مفسر', 'fawaid_sawtiyah_sh_albukhary_269.mp3'),
            ('ضوابط القارئ الذي يتلقى عنه القرآن', 'fawaid_sawtiyah_sh_albukhary_268.mp3'),
            ('بيان خطأ الطالب الجامعي الذي يفرط في دراسته النظامية بدعوى أنها لا تفيد', 'fawaid_sawtiyah_sh_albukhary_267.mp3'),
            ('بيان بطلان تقسيم الباحثين الفرنسيين للسلفية', 'fawaid_sawtiyah_sh_albukhary_266.mp3'),
            ('وجوب الالتزام بـنظام حملة إغاثة الشعب السوري التي أمر بها الملك سلمان حفظه الله', 'fawaid_sawtiyah_sh_albukhary_265.mp3'),
            ('كيف يوطن المرء نفسه على الرجوع عن الخطأ والزلل إن وقع منه؟', 'fawaid_sawtiyah_sh_albukhary_264.mp3'),
            ('تسجيل كلام الشيخ بغير إذنه مخالف للأمانة', 'fawaid_sawtiyah_sh_albukhary_263.mp3'),
            ('هل مكوث الطالب وعدم عودته لبلده في الإجازة لطلب العلم يعد من عقوق الوالدين؟', 'fawaid_sawtiyah_sh_albukhary_262.mp3'),
            ('التحذير من التفريط في بر الوالدين وعقوقهما', 'fawaid_sawtiyah_sh_albukhary_261.mp3'),
            ('أهمية الاجتماع على الحق ونبذ الفرقة والاختلاف', 'fawaid_sawtiyah_sh_albukhary_260.mp3'),
            ('أهمية العناية بالقرآن لطالب العلم', 'fawaid_sawtiyah_sh_albukhary_259.mp3'),
            ('هل يستحب للمرأة لبس اللون الأسود من العباءات؟', 'fawaid_sawtiyah_sh_albukhary_258.mp3'),
            ('حكم بيع ربطة العنق (الكرافتة)', 'fawaid_sawtiyah_sh_albukhary_257.mp3'),
            ('حكم الترحم على من لم يكن يصلي على الدوام', 'fawaid_sawtiyah_sh_albukhary_256.mp3'),
            ('حكم استخدام ماء زمزم لغسل الميت', 'fawaid_sawtiyah_sh_albukhary_255.mp3'),
            ('هل ورد في دخول السوق دعاء صحيح؟', 'fawaid_sawtiyah_sh_albukhary_254.mp3'),
            ('حكم إقامة المظاهرات في بلاد الكفر لنصرة المسلمين في الشام', 'fawaid_sawtiyah_sh_albukhary_253.mp3'),
            ('بطلان الاحتجاج بتزكية الإمام الشافعي لإبراهيم بن أبي يحيى على عدم التقاطع', 'fawaid_sawtiyah_sh_albukhary_252.mp3'),
            ('نقد مسلك من يستغل كلام المشايخ في التحذير من الغيبة ضد من يحذر من الأخطاء', 'fawaid_sawtiyah_sh_albukhary_251.mp3'),
            ('الرد على من يتكلم في الحكومة السعودية بسبب دورها في أحداث حلب', 'fawaid_sawtiyah_sh_albukhary_250.mp3'),
            ('معنى حديث «إذا كان جنح الليل فكفوا صبيانكم»', 'fawaid_sawtiyah_sh_albukhary_249.mp3'),
            ('نصيحة لمن يأتي لأخيه ماكرا ليأخذ منه أخبارا فيفضحه دون علمه', 'fawaid_sawtiyah_sh_albukhary_248.mp3'),
            ('بطلان القول بأن الزيدية مذهب من مذاهب أهل السنة', 'fawaid_sawtiyah_sh_albukhary_247.mp3'),
            ('توجيه ما ورد عن السلف من تفضيل الأدب على تعلم العلم', 'fawaid_sawtiyah_sh_albukhary_246.mp3'),
            ('تعليق مختصر على بدعة الاحتفال بالمولد النبوي', 'fawaid_sawtiyah_sh_albukhary_245.mp3'),
            ('حكم طرد من يثير الشبهات من المسجد حفاظا على عقيدة المصلين', 'fawaid_sawtiyah_sh_albukhary_244.mp3'),
            ('التحذير من التوسع في التصوير', 'fawaid_sawtiyah_sh_albukhary_243.mp3'),
            ('نصيحة لمن طلق امرأة سلفية وتزوج امرأة غير مستقيمة', 'fawaid_sawtiyah_sh_albukhary_242.mp3'),
            ('نصيحة في كيفية معاملة الأخ التارك للصلاة', 'fawaid_sawtiyah_sh_albukhary_241.mp3'),
            ('أهمية تدوين الفوائد أثناء الدروس العلمية لطالب العلم', 'fawaid_sawtiyah_sh_albukhary_240.mp3'),
            ('كشف شبهة من يدعي أن المملكة العربية السعودية خرجت على الدولة العثمانية', 'fawaid_sawtiyah_sh_albukhary_239.mp3'),
            ('هل يجوز لصاحب الدين أن يخصم الدين من مال الزكاة إذا لا يرجى رده؟', 'fawaid_sawtiyah_sh_albukhary_238.mp3'),
            ('نصيحة لمن ابتلي بالسكن مع شخص يطعن في العلماء', 'fawaid_sawtiyah_sh_albukhary_237.mp3'),
            ('نصيحة للزوجة التي تتكاسل في خدمة زوجها', 'fawaid_sawtiyah_sh_albukhary_236.mp3'),
            ('خطأ من لا يلصق قدمه بقدم من بجانبه في الصف إلا في الركوع', 'fawaid_sawtiyah_sh_albukhary_235.mp3'),
            ('حكم أداء صلاة الجماعة في مصلى الشركة', 'fawaid_sawtiyah_sh_albukhary_234.mp3'),
            ('هل أسانيد كتب التفسير تعامل معاملة أسانيد كتب الحديث؟', 'fawaid_sawtiyah_sh_albukhary_233.mp3'),
            ('نصيحة لطلبة العلم باستغلال الإجازة للمذاكرة', 'fawaid_sawtiyah_sh_albukhary_232.mp3'),
            ('حكم مطالبة الزوجة بالطلاق لإصرار زوجها على مشاهدة الأفلام الخليعة', 'fawaid_sawtiyah_sh_albukhary_231.mp3'),
            ('حكم قضاء الصلوات الفائتة لمن تركها تهاونا ثم تاب', 'fawaid_sawtiyah_sh_albukhary_230.mp3'),
            ('حكم تنصت الزوج على مكالمات زوجته', 'fawaid_sawtiyah_sh_albukhary_229.mp3'),
            ('حكم تسميع المتون العلمية على المجاهيل والمخالفين', 'fawaid_sawtiyah_sh_albukhary_228.mp3'),
            ('حكم الاعتمار من المرتب الذي تعطيه الدولة الكافرة للعاجزين عن العمل', 'fawaid_sawtiyah_sh_albukhary_227.mp3'),
            ('حكم أداء مغسلي الأموات صلاة الجنازة على الميت بعد تغسيله قبل الجنازة العامة', 'fawaid_sawtiyah_sh_albukhary_226.mp3'),
            ('حكم أخذ المهدئات لمن أصيب بمرض اضطراب نقص الانتباه', 'fawaid_sawtiyah_sh_albukhary_225.mp3'),
            ('الطريقة الصحيحة لحفظ القرآن', 'fawaid_sawtiyah_sh_albukhary_224.mp3'),
            ('نصيحة للمسلمين في إندونيسيا حول المظاهرة المقامة في جاكرتا', 'fawaid_sawtiyah_sh_albukhary_223.mp3'),
            ('كيفية التعامل مع امرأة ارتدت عن الإسلام في دولة غربية', 'fawaid_sawtiyah_sh_albukhary_222.mp3'),
            ('بطلان دعوى اختلاف منهج المحدثين المتأخرين عن منهج المحدثين المتقدمين', 'fawaid_sawtiyah_sh_albukhary_221.mp3'),
            ('الحث على بر الوالدين وذم من يقصر في ذلك', 'fawaid_sawtiyah_sh_albukhary_220.mp3'),
            ('التنبيه على خطأ من يقرر صورة انتفاء الإرادة الشرعية والإرادة الكونية معا', 'fawaid_sawtiyah_sh_albukhary_219.mp3'),
            ('نصيحة لمن ابتلي بإدمان الجوال', 'fawaid_sawtiyah_sh_albukhary_217.mp3'),
            ('بيان زندقة الرافضي الخبيث ياسر الحبيب', 'fawaid_sawtiyah_sh_albukhary_218.mp3'),
            ('بيان انحراف المدعو عدنان إبراهيم عن منهج أهل السنة والجماعة', 'fawaid_sawtiyah_sh_albukhary_216.mp3'),
            ('حكم اعتمار المرأة عن زوجها المعتقل في أحد سجون العراق', 'fawaid_sawtiyah_sh_albukhary_215.mp3'),
            ('التحذير من المعلم الذي ثبت أنه يكذب', 'fawaid_sawtiyah_sh_albukhary_214.mp3'),
            ('حكم استفتاء أكثر من عالم في قضية واحدة', 'fawaid_sawtiyah_sh_albukhary_213.mp3'),
            ('خطأ من ينزل فتاوى العلماء في غير مواطنها ويفسرها برأيه', 'fawaid_sawtiyah_sh_albukhary_212.mp3'),
            ('تبرئة السلفيين من الأعمال الإرهابية ونهج الخوارج', 'fawaid_sawtiyah_sh_albukhary_211.mp3'),
            ('نصيحة لمن يعيش في بلد ليس فيه علماء وفي زمن كثرت فيه الفتن', 'fawaid_sawtiyah_sh_albukhary_208.mp3'),
            ('نصيحة لرجل أصم يريد أن يطلب العلم', 'fawaid_sawtiyah_sh_albukhary_210.mp3'),
            ('الطريقة الصحيحة لاستفهام الطالب شيخه عما استشكله من كلامه', 'fawaid_sawtiyah_sh_albukhary_209.mp3'),
            ('نصيحة لمن يريد أن يطلب العلم ليصلح نفسه لكن أصدقاءه يسخرون منه', 'fawaid_sawtiyah_sh_albukhary_207.mp3'),
            ('حكم وضع صندوق في المسجد لأجل التبرع لصالح المسجد', 'fawaid_sawtiyah_sh_albukhary_206.mp3'),
            ('حكم مرتب الموظف الذي لا يذهب إلى عمله إلا يوما واحدا في الأسبوع بطلب من المدير', 'fawaid_sawtiyah_sh_albukhary_205.mp3'),
            ('حكم الأخذ من مياه زمزم الموجودة في المسجد النبوي والذهاب بها إلى الفنادق', 'fawaid_sawtiyah_sh_albukhary_204.mp3'),
            ('رجل قدم إلى السعودية لأداء عمرة وبعد وصوله تذكر أن عليه دينا فهل تصح عمرته؟', 'fawaid_sawtiyah_sh_albukhary_203.mp3'),
            ('هل الأفضل في السفر الصوم أو الفطر؟', 'fawaid_sawtiyah_sh_albukhary_202.mp3'),
            ('أولاد يعملون لكسب معيشة الأسرة ويخشى عليهم من الهلاك إن صاموا فهل يبيح لهم الفطر؟', 'fawaid_sawtiyah_sh_albukhary_201.mp3'),
            ('حكم صيام من شرب بعد أذان الفجر ظانا أنه لم يؤذن بعد', 'fawaid_sawtiyah_sh_albukhary_200.mp3'),
            ('نصيحة لشاب يكرهه والده الكافر على الإفطار في رمضان', 'fawaid_sawtiyah_sh_albukhary_199.mp3'),
            ('المراد بالوعيد الوارد في قول النبي ﷺ: «مات ميتة جاهلية»', 'fawaid_sawtiyah_sh_albukhary_198.mp3'),
            ('حكم إعطاء المال الذي هو وقف للمسجد لمسجد آخر يحتاجه', 'fawaid_sawtiyah_sh_albukhary_197.mp3'),
            ('بماذا يكون تفطير الصائم الذي ورد فضله في الحديث؟', 'fawaid_sawtiyah_sh_albukhary_196.mp3'),
            ('متى يكون الإمساك في الدولة التي يؤخر فيها أذان الفجر في رمضان؟', 'fawaid_sawtiyah_sh_albukhary_195.mp3'),
            ('امرأة حامل تحتاج إلى أخذ الدواء ولا تستطيع الصوم فهل تقضي أو تطعم؟', 'fawaid_sawtiyah_sh_albukhary_194.mp3'),
            ('حكم ختان البنات', 'fawaid_sawtiyah_sh_albukhary_193.mp3'),
            ('حكم حلق رأس البنت في يوم عقيقتها', 'fawaid_sawtiyah_sh_albukhary_192.mp3'),
            ('هل يجوز قضاء الدين عن الميت إذا أوصى أن يكون ذلك من مرتبه الشهري؟', 'fawaid_sawtiyah_sh_albukhary_191.mp3'),
            ('أيهما يقدم طلب العلم أو قضاء الدين؟', 'fawaid_sawtiyah_sh_albukhary_190.mp3'),
            ('الدليل على عقد التسبيح باليد اليمنى', 'fawaid_sawtiyah_sh_albukhary_189.mp3'),
            ('حكم تكرار العمرة بعد الخروج من حدود المواقيت', 'fawaid_sawtiyah_sh_albukhary_188.mp3'),
            ('جمع طالب العلم بين مراجعة محفوظاته وتلاوة القرآن في رمضان', 'fawaid_sawtiyah_sh_albukhary_187.mp3'),
            ('هل يجب تبليغ المراقب بالطالب الذي يغش في الاختبار؟', 'fawaid_sawtiyah_sh_albukhary_186.mp3'),
            ('حكم الحج عن الجدة الكبيرة في السن', 'fawaid_sawtiyah_sh_albukhary_185.mp3'),
            ('حكم لبس القميص في بلد لم يعتد فيه لبسه', 'fawaid_sawtiyah_sh_albukhary_184.mp3'),
            ('بطلان اتفاق الرجل مع زوجته الثانية على عدم قيامه بالعدل بينها وبين زوجته الأولى', 'fawaid_sawtiyah_sh_albukhary_183.mp3'),
            ('وصية لطلاب العلم بالعناية بتحسين الأخلاق والآداب', 'fawaid_sawtiyah_sh_albukhary_182.mp3'),
            ('حكم زيارة جميع الزوجات في يوم العودة من السفر', 'fawaid_sawtiyah_sh_albukhary_181.mp3'),
            ('عدة المرأة التي طلقت بعد الولادة', 'fawaid_sawtiyah_sh_albukhary_180.mp3'),
            ('حكم غسل لباس الإحرام بالصابون المعطر', 'fawaid_sawtiyah_sh_albukhary_179.mp3'),
            ('حكم تحريك السبابة في التشهد في الصلاة', 'fawaid_sawtiyah_sh_albukhary_178.mp3'),
            ('معنى مصطلح (صيغة التمريض)', 'fawaid_sawtiyah_sh_albukhary_177.mp3'),
            ('ضابط المجالسة الممرضة للقلوب', 'fawaid_sawtiyah_sh_albukhary_176.mp3'),
            ('هل يوجز للداخل للمسجد أولا أن يؤذن مع وجود مؤذن راتب؟', 'fawaid_sawtiyah_sh_albukhary_175.mp3'),
            ('هل يشرع حب الوطن للمسلم الذي ولد في دولة كافرة؟', 'fawaid_sawtiyah_sh_albukhary_174.mp3'),
            ('هل يجوز للرجل أن ينظر للمرأة التي يريد أن يخطبها عبر (سكايب)؟', 'fawaid_sawtiyah_sh_albukhary_173.mp3'),
            ('هل استنشاق البخور يفظر الصائم؟', 'fawaid_sawtiyah_sh_albukhary_172.mp3'),
            ('صفة الرقية الواردة في حديث «تربة أرضنا بريقة بعضنا»', 'fawaid_sawtiyah_sh_albukhary_171.mp3'),
            ('حكم قطع الصلاة لمساعدة من غشي عليه', 'fawaid_sawtiyah_sh_albukhary_170.mp3'),
            ('ما رأيكم في كتاب (إحياء علوم الدين) للغزالي؟', 'fawaid_sawtiyah_sh_albukhary_169.mp3'),
            ('كيف يحفظ طالب العلم أحاديث بلوغ المرام أو المحرر؟', 'fawaid_sawtiyah_sh_albukhary_168.mp3'),
            ('ما هي كتب مصطلح الحديث التي يدرسها ويحفظها طالب العلم؟', 'fawaid_sawtiyah_sh_albukhary_167.mp3'),
            ('الفوائد التي يحصلها طالب العلم من كتب التخريج', 'fawaid_sawtiyah_sh_albukhary_166.mp3'),
            ('بطلان تحريف ابن فورك لصفة الغيرة لله', 'fawaid_sawtiyah_sh_albukhary_165.mp3'),
            ('حكم المسجد الذي بني على أرض تركتها الدولة متنفسا للناس بغير إذن منها', 'fawaid_sawtiyah_sh_albukhary_164.mp3'),
            ('حكم تقديم الألعاب والطعام في فناء المسجد لأجل جمع التبرعات للمسجد', 'fawaid_sawtiyah_sh_albukhary_163.mp3'),
            ('امرأة حامل يأمرها زوجها بإسقاط الجنين خوفا عليها، فهل تطيعه؟', 'fawaid_sawtiyah_sh_albukhary_162.mp3'),
            ('كيفية تطبيق أحكام الولاء والبراء في بلد الكفر ومع الأقارب الكفار', 'fawaid_sawtiyah_sh_albukhary_161.mp3'),
            ('هل يصح القول بأن العالم قد يحذر من منهج الشخص لا من عقيدته؟', 'fawaid_sawtiyah_sh_albukhary_160.mp3'),
            ('مصنع تتعطل فيه آلة كل يوم من عين، فكيف يرقيه صاحبه؟', 'fawaid_sawtiyah_sh_albukhary_159.mp3'),
            ('نصيحة لمن هاجر  بأسرته من بلد الكفر إلى بلد الإسلام ثم رجع لكسب العيش', 'fawaid_sawtiyah_sh_albukhary_158.mp3'),
            ('حكم حضور اجتماع الأقارب الكفار في عيد رأس السنة بنية صلة الرحم', 'fawaid_sawtiyah_sh_albukhary_157.mp3'),
            ('ما صحة القول بأنا لا نحذر حديث الاستقامة من جماعة التبليغ خوفا من تنفيره؟', 'fawaid_sawtiyah_sh_albukhary_156.mp3'),
            ('حكم زيادة «وطيب صلواته» في رد السلام', 'fawaid_sawtiyah_sh_albukhary_155.mp3'),
            ('ما هو أفضل كتاب في علم مصطلح الحديث؟', 'fawaid_sawtiyah_sh_albukhary_154.mp3'),
            ('حكم أكل الدجاج المستورد', 'fawaid_sawtiyah_sh_albukhary_153.mp3'),
            ('أحيانا أستشعر حصول شيء بمجرد إحساس، فهل يعتبر من الفراسة أو من الكهانة؟', 'fawaid_sawtiyah_sh_albukhary_152.mp3'),
            ('هل تجب صلاة الجماعة على من سافر إلى مكان يمكث فيه مدة غير معلومة؟', 'fawaid_sawtiyah_sh_albukhary_151.mp3'),
            ('النصيحة للزوج الذي ينشغل بالجوال عن تربية أولاده ويتخلف عن صلاة الجماعة', 'fawaid_sawtiyah_sh_albukhary_150.mp3'),
            ('معنى قول السلف: «طلبنا العلم لغير الله وأبى أن يكون إلا لله»', 'fawaid_sawtiyah_sh_albukhary_149.mp3'),
            ('هل السنة حجة في باب الاعتقاد؟', 'fawaid_sawtiyah_sh_albukhary_148.mp3'),
            ('الرد على الصوفي الذي ادعى أن الأدب مقدم على الاتباع', 'fawaid_sawtiyah_sh_albukhary_147.mp3'),
            ('مذاهب أهل العلم في معنعنات المدلسين في الصحيحين', 'fawaid_sawtiyah_sh_albukhary_146.mp3'),
            ('هل يكون الزوج كافرا للعشير؟', 'fawaid_sawtiyah_sh_albukhary_145.mp3'),
            ('هل الأفضل صلاة السنن الرواتب في البيت أو في المسجد؟', 'fawaid_sawtiyah_sh_albukhary_144.mp3'),
            ('هل الأحسن التفقه على المتون الفقهية أو على المتون الحديثية؟', 'fawaid_sawtiyah_sh_albukhary_143.mp3'),
            ('حكم صلاة من صلى في مسجد فيه قبر بدون علم به', 'fawaid_sawtiyah_sh_albukhary_142.mp3'),
            ('حكم صلاة التسابيح', 'fawaid_sawtiyah_sh_albukhary_141.mp3'),
            ('حكم اشتراط مؤجر الشقة على المستأجر اشتراء العفش الموجود فيها', 'fawaid_sawtiyah_sh_albukhary_140.mp3'),
            ('الرد على من يزعم أن فخد الرجل ليس عورة لأن النبي ﷺ كشفه أمام أصحابه', 'fawaid_sawtiyah_sh_albukhary_139.mp3'),
            ('شاب كان يتعلم مع السلفيين فمنعه والده خوفا عليه من السلفيين فماذا يصنع؟', 'fawaid_sawtiyah_sh_albukhary_138.mp3'),
            ('نصيحة للسلفيين بخصوص أفعال داعش الإجرامية في التونس', 'fawaid_sawtiyah_sh_albukhary_137.mp3'),
            ('هل الخمر نجسة؟', 'fawaid_sawtiyah_sh_albukhary_136.mp3'),
            ('ما صحة القول بتحريم المشروبات الغازية بدعوى أن فيها ضررا على الجسم؟', 'fawaid_sawtiyah_sh_albukhary_135.mp3'),
            ('حكم إعطاء طلاب المعاهد المصاحف الموقوفة للقراءة في المسجد', 'fawaid_sawtiyah_sh_albukhary_134.mp3'),
            ('فتح قبر رجل مات قبل أكثر من عشرين سنة فوجدوا جثته لم تتحلل، فهل يدل أنه من أهل الجنة؟', 'fawaid_sawtiyah_sh_albukhary_133.mp3'),
            ('ما صحة الدعوى بأن أخطاء الحكام فادحة تدور بين الكفر والفسق', 'fawaid_sawtiyah_sh_albukhary_132.mp3'),
            ('خطيب في فرنسا يقول للحاضرين: كلكم سلفيون، فهل هذا صحيح؟', 'fawaid_sawtiyah_sh_albukhary_131.mp3'),
            ('هل أئمة المساجد يعدون ولاة لأمور المسلمين في الدول الكافرة؟', 'fawaid_sawtiyah_sh_albukhary_130.mp3'),
            ('بطلان الاستدلال بقصة أبي هريرة مع الشيطان على تلقي العلم عن كل شخص', 'fawaid_sawtiyah_sh_albukhary_129.mp3'),
            ('الرد على من يزعم أنه لا دليل على جرح الدعاة من أهل البدع', 'fawaid_sawtiyah_sh_albukhary_128.mp3'),
            ('حكم التسمية عند الذبح وهل هي شرط لحل لحم الذبيحة', 'fawaid_sawtiyah_sh_albukhary_127.mp3'),
            ('تحقيق التقوى وثماره', 'fawaid_sawtiyah_sh_albukhary_126.mp3'),
            ('موعظة قصيرة عن ضرر التدخين', 'fawaid_sawtiyah_sh_albukhary_125.mp3'),
            ('هل مرشد المعتمرين يبين لهم حكم حلق اللحية أو يركز على العقيدة؟', 'fawaid_sawtiyah_sh_albukhary_124.mp3'),
            ('حكم رفع الصوت بأذكار المناسك في المسجد لتعليم العوام', 'fawaid_sawtiyah_sh_albukhary_123.mp3'),
            ('تنبيه من الشيخ البخاري يتعلق بالنقل عنه', 'fawaid_sawtiyah_sh_albukhary_122.mp3'),
            ('هل نقبل الحق الذي جاء به سيد قطب كما قبلناه من النووي؟', 'fawaid_sawtiyah_sh_albukhary_121.mp3'),
            ('حكم الذهاب إلى الأفراح التي فيها جملة من المنكرات', 'fawaid_sawtiyah_sh_albukhary_120.mp3'),
            ('هل نصوص الصفات من المحكم أو المتشابه؟', 'fawaid_sawtiyah_sh_albukhary_119.mp3'),
            ('هل يسن للمسافر أن يصلي الرواتب؟', 'fawaid_sawtiyah_sh_albukhary_118.mp3'),
            ('هل نجزم بأن ما في الصحيحين قد قاله رسول الله ﷺ؟', 'fawaid_sawtiyah_sh_albukhary_117.mp3'),
            ('كيفية رد السلام أثناء الصلاة', 'fawaid_sawtiyah_sh_albukhary_116.mp3'),
            ('حكم الاتكاء أثناء الخطبة', 'fawaid_sawtiyah_sh_albukhary_115.mp3'),
            ('حكم إلقاء السلام على الخطيب والمستمعين أثناء الخطبة', 'fawaid_sawtiyah_sh_albukhary_114.mp3'),
            ('هل يجب الإنصات إلى الخطباء المخالفين للمنهج السلفي؟', 'fawaid_sawtiyah_sh_albukhary_113.mp3'),
            ('كيف نكون دوماً على الحق؟', 'fawaid_sawtiyah_sh_albukhary_112.mp3'),
            ('الرد على من يزعم أن الواقع يكذب أن أخبار الآحاد الصحيحة تفيد العلم', 'fawaid_sawtiyah_sh_albukhary_111.mp3'),
            ('هل صحيح أن الرجل الذي يشقه الدجال نصفين هو الخضر؟', 'fawaid_sawtiyah_sh_albukhary_110.mp3'),
            ('بطلان قول بعض المدرسين: أنا إخواني، تبليغي، سلفي', 'fawaid_sawtiyah_sh_albukhary_109.mp3'),
            ('كيفية معاملة الزميلات المتأثرات بالقصاصين', 'fawaid_sawtiyah_sh_albukhary_108.mp3'),
            ('نصيحة لأخت سلفية في كيفية معاملة والدها الإخواني', 'fawaid_sawtiyah_sh_albukhary_107.mp3'),
            ('معنى قول الإمام أحمد: ثلاثة علوم ليس لها أصل', 'fawaid_sawtiyah_sh_albukhary_106.mp3'),
            ('توضيح كلام للإمام ابن القيم في وصف أهل السنة', 'fawaid_sawtiyah_sh_albukhary_105.mp3'),
            ('بعض الكتب المفيدة في بيان معتقد الرافضة والرد عليهم', 'fawaid_sawtiyah_sh_albukhary_104.mp3'),
            ('كيفية معاملة المدرس الذي يرسل مقاطع لأهل البدع', 'fawaid_sawtiyah_sh_albukhary_103.mp3'),
            ('الضابط في الصبر على الأخطاء الصادرة من السلفي', 'fawaid_sawtiyah_sh_albukhary_102.mp3'),
            ('نصيحة في كيفية تعامل طلاب العلم فيما بينهم', 'fawaid_sawtiyah_sh_albukhary_101.mp3'),
            ('بطلان الدعوى أنه يلزم من تطبيق آثار السلف في هجر المبتدعة التبديع التسلسلي', 'fawaid_sawtiyah_sh_albukhary_100.mp3'),
            ('كيفية معاملة الطلاب العوام والذين يحضرون عند المخالفين', 'fawaid_sawtiyah_sh_albukhary_099.mp3'),
            ('حكم الاستفادة من كتاب مؤلفه مجهول', 'fawaid_sawtiyah_sh_albukhary_098.mp3'),
            ('كيف يتعلم طالب العلم تخريج الأحاديث؟', 'fawaid_sawtiyah_sh_albukhary_097.mp3'),
            ('بطلان الدعوى أنه لا فرق بين طلب العلم عند العلماء وبين طلبه على الكتب والأشرطة', 'fawaid_sawtiyah_sh_albukhary_096.mp3'),
            ('كيف يصبح طالب العلم راسخاً في العلم؟', 'fawaid_sawtiyah_sh_albukhary_095.mp3'),
            ('حكم تقييم طلبة العلم مكانة مشايخهم العلمية', 'fawaid_sawtiyah_sh_albukhary_094.mp3'),
            ('حكم مقولة: «إن الإسلام دين دموي»', 'fawaid_sawtiyah_sh_albukhary_093.mp3'),
            ('كيفية تعليم العوام والأعاجم المنهج والمعتقد السلفي', 'fawaid_sawtiyah_sh_albukhary_092.mp3'),
            ('الفرق بين نشر المقالات العلمية سابقا وبين نشرها اليوم', 'fawaid_sawtiyah_sh_albukhary_091.mp3'),
            ('حكم الاعتماد على الكتب والبرامج الالكترونية في العزو', 'fawaid_sawtiyah_sh_albukhary_090.mp3'),
            ('حكم تسجيل كلام المشايخ سرا ونشره بدون إذنهم', 'fawaid_sawtiyah_sh_albukhary_089.mp3'),
            ('هل مسائل الجرح والتعديل اجتهادية؟', 'fawaid_sawtiyah_sh_albukhary_088.mp3'),
            ('هل خلع الخفين بعد المسح عليهما ينقض الوضوء؟', 'fawaid_sawtiyah_sh_albukhary_087.mp3'),
            ('هل العمدة رئيس البلدية يعتبر ولي أمر؟', 'fawaid_sawtiyah_sh_albukhary_086.mp3'),
            ('حكم شراء الألبسة والأجهزة في أوقات أعياد الميلاد لأجل التخفيضات', 'fawaid_sawtiyah_sh_albukhary_085.mp3'),
            ('حكم تقصير الثوب إلى نصف الساق إذا خالف ذلك عادة البلد', 'fawaid_sawtiyah_sh_albukhary_084.mp3'),
            ('حكم أكل الحلوى التي من ضمن محتوياتها نسبة من الكحول', 'fawaid_sawtiyah_sh_albukhary_083.mp3'),
            ('هل يجب على من دخل مكة أداء العمرة أو يجزئه الطواف؟', 'fawaid_sawtiyah_sh_albukhary_082.mp3'),
            ('هل يجب خلع الجوربين إذا لبسهما فوق جوربين آخرين عند المسح عليها؟', 'fawaid_sawtiyah_sh_albukhary_081.mp3'),
            ('هل لمس فرج الطفل عند تنظيفه ناقض للوضوء؟', 'fawaid_sawtiyah_sh_albukhary_080.mp3'),
            ('نصيحة لمن ابتلي بتكرار فعل المعصية في الخلوة', 'fawaid_sawtiyah_sh_albukhary_079.mp3'),
            ('ما هي أفضل الكليات للطالب المتخرج من معهد اللغة؟', 'fawaid_sawtiyah_sh_albukhary_078.mp3'),
            ('حكم مقولة: أن تحركني قصيدة للجهاد خير لي من أن أسمع مئة ألف حديثا تخذلني عن الجهاد', 'fawaid_sawtiyah_sh_albukhary_077.mp3'),
            ('حكم كشف وجه الميت ليراه الناس', 'fawaid_sawtiyah_sh_albukhary_076.mp3'),
            ('حكم فرق الشعر على الجانب للنساء', 'fawaid_sawtiyah_sh_albukhary_075.mp3'),
            ('حكم الأكل من الطعام الذي يصنعه أهل الميت في العزاء أو الأربعينية', 'fawaid_sawtiyah_sh_albukhary_074.mp3'),
            ('حكم إسقاط الجنين للمرأة التي لا يطيق جسمها الحمل بسبب تقارب الولادات', 'fawaid_sawtiyah_sh_albukhary_073.mp3'),
            ('طالب درس على شخص قد انحرف فهل يذكر دراسته عليه؟', 'fawaid_sawtiyah_sh_albukhary_072.mp3'),
            ('حكم صدقة يسيرة لرجل عليه ديون كثيرة', 'fawaid_sawtiyah_sh_albukhary_071.mp3'),
            ('لماذا ينقمون على الشيخ ربيع المدخلي؟', 'fawaid_sawtiyah_sh_albukhary_070.mp3'),
            ('كلمة توجيهية عن حادثة التدافع في مشعر منى', 'fawaid_sawtiyah_sh_albukhary_069.mp3'),
            ('توجيه حول اختلاف الطلاب في تعليم الناس في بلدهم', 'fawaid_sawtiyah_sh_albukhary_068.mp3'),
            ('كيفية التعامل مع الطالب الذي لا يقبل تراجع الشخص إذا أخطأ', 'fawaid_sawtiyah_sh_albukhary_067.mp3'),
            ('حكم نسخ دروس العلماء على أقراص وبيعها بدون استئذانهم', 'fawaid_sawtiyah_sh_albukhary_066.mp3'),
            ('حكم ترك صلاة الجماعة لحراسة الأحذية من السرقة', 'fawaid_sawtiyah_sh_albukhary_065.mp3'),
            ('حكم الرسوب في الامتحانات متعمدا لأجل البقاء في المدينة مدة أطول', 'fawaid_sawtiyah_sh_albukhary_064.mp3'),
            ('حكم استعمال جوز الطيب في الأطعمة', 'fawaid_sawtiyah_sh_albukhary_063.mp3'),
            ('حكم استرجاع الأم ذهبا أهدته لبنتها', 'fawaid_sawtiyah_sh_albukhary_062.mp3'),
            ('حكم استبدال لفظ «رسول الله» بلفظ «النبي» عندي تسميع الأحاديث', 'fawaid_sawtiyah_sh_albukhary_061.mp3'),
            ('حكم إزالة الوشم بالعملية أو بالطمس', 'fawaid_sawtiyah_sh_albukhary_060.mp3'),
            ('هل فريضة الحج على الفور أو على التراخي؟', 'fawaid_sawtiyah_sh_albukhary_059.mp3'),
            ('وجوب الالتزام بأنظمة الحج التي وضعها ولي الأمر', 'fawaid_sawtiyah_sh_albukhary_058.mp3'),
            ('هل يصح أن يكون اشتراط عدم التعدد مهرا؟', 'fawaid_sawtiyah_sh_albukhary_057.mp3'),
            ('هل يجوز للسوريين السفر إلى بلاد الكفر لأجل وضع بلدهم؟', 'fawaid_sawtiyah_sh_albukhary_056.mp3'),
            ('هل يجب التواصل مع الأقارب؟', 'fawaid_sawtiyah_sh_albukhary_055.mp3'),
            ('هل ورد شيء في فضل طلب العلم بالمدينة؟', 'fawaid_sawtiyah_sh_albukhary_054.mp3'),
            ('هل العَسْل من صفات الله؟', 'fawaid_sawtiyah_sh_albukhary_053.mp3'),
            ('ما صحة حديث من كان له إمام فقراءة الإمام قراءة له؟', 'fawaid_sawtiyah_sh_albukhary_052.mp3'),
            ('الرقية الجماعية باستعمال الميكروفون من البدع والحوادث', 'fawaid_sawtiyah_sh_albukhary_051.mp3'),
            ('هل الأفضل أن يرقي المرء نفسه أو يرقيه غيره؟', 'fawaid_sawtiyah_sh_albukhary_050.mp3'),
            ('حكم التصدق على المحتاجين بمضخات يظنها مسروقة', 'fawaid_sawtiyah_sh_albukhary_049.mp3'),
            ('حكم الاستدلال بفعل العالم', 'fawaid_sawtiyah_sh_albukhary_048.mp3'),
            ('حكم اشتراء عمارة عليها قرض ربوي', 'fawaid_sawtiyah_sh_albukhary_047.mp3'),
            ('حكم إسقاط الحمل خشية فقد الأم بصرها', 'fawaid_sawtiyah_sh_albukhary_046.mp3'),
            ('حكم استعمال الحبوب المانعة من الحمل للمرأة التي اشترطت إكمال دراستها عند الزواج', 'fawaid_sawtiyah_sh_albukhary_045.mp3'),
            ('بطلان زعم الزاعم بأن تصحيح المشايخ لتوبة فلان صكوك غفران', 'fawaid_sawtiyah_sh_albukhary_044.mp3'),
            ('التعليق على قول من يقول إن الانتصارات التي حدثت لأهل السنة على الحوثة هي انتصارات إلى جهنم', 'fawaid_sawtiyah_sh_albukhary_043.mp3'),
            ('إنما يزكي المرء عمله', 'fawaid_sawtiyah_sh_albukhary_042.mp3'),
            ('حكم دفع الزكاة للقنوات الفضائية', 'fawaid_sawtiyah_sh_albukhary_041.mp3'),
            ('نصيحة لمن يريد الزواج لكن والديه يرفضان', 'fawaid_sawtiyah_sh_albukhary_040.mp3'),
            ('حكم صوم من قاء بسبب عمل المنظار للجهاز الهضمي', 'fawaid_sawtiyah_sh_albukhary_039.mp3'),
            ('حكم إخراج كفارة الحلف نيابة عن الأم', 'fawaid_sawtiyah_sh_albukhary_038.mp3'),
            ('متى يجب حسن الظن بالمسلم؟', 'fawaid_sawtiyah_sh_albukhary_037.mp3'),
            ('أيهما أفضل في السحر الاستغفار أو قراءة القرآن؟', 'fawaid_sawtiyah_sh_albukhary_036.mp3'),
            ('ألح في الدعاء فلم يستجب له فما السبب؟', 'fawaid_sawtiyah_sh_albukhary_035.mp3'),
            ('استعمل ماله في تجارة قبل أن يبلغ الحول بشهر فهل فيه زكاة؟', 'fawaid_sawtiyah_sh_albukhary_034.mp3'),
            ('حكم أداء صلاة التراويح في مساجد أهل البدع', 'fawaid_sawtiyah_sh_albukhary_033.mp3'),
            ('حكم رد السلام بلفظ: &#8220;وعليكم أفضل السلام&#8221;', 'fawaid_sawtiyah_sh_albukhary_032.mp3'),
            ('حكم الإطعام عمن لا يدري هل يزول مرضه أو لا', 'fawaid_sawtiyah_sh_albukhary_031.mp3'),
            ('حكم إضافة مسجد إلى مركز توفي واقفه', 'fawaid_sawtiyah_sh_albukhary_030.mp3'),
            ('التحذير من جماعة التبليغ', 'fawaid_sawtiyah_sh_albukhary_029.mp3'),
            ('حكم إحضار المرأة الأطفال المشوشين إلى المسجد', 'fawaid_sawtiyah_sh_albukhary_028.mp3'),
            ('هل الدعاء حين الإفطار لا يرد؟', 'fawaid_sawtiyah_sh_albukhary_027.mp3'),
            ('نصيحة في استغلال شهر رمضان', 'fawaid_sawtiyah_sh_albukhary_026.mp3'),
            ('ضابط المسائل التي يرجع فيها طالب العلم للعلماء', 'fawaid_sawtiyah_sh_albukhary_025.mp3'),
            ('حكم العمل في الجهات الرسمية التي تحت الحزبيين', 'fawaid_sawtiyah_sh_albukhary_024.mp3'),
            ('بغض أهل البدع', 'fawaid_sawtiyah_sh_albukhary_023.mp3'),
            ('أهمية عناية طالب العلم بتعليم أسرته', 'fawaid_sawtiyah_sh_albukhary_022.mp3'),
            ('الكتب التي ينصح بدراستها لتعلم منهج السلف', 'fawaid_sawtiyah_sh_albukhary_021.mp3'),
            ('المفاضلة بين ألفية العراقي وألفية السيوطي', 'fawaid_sawtiyah_sh_albukhary_020.mp3'),
            ('حظ طالب العلم من كتب الردود وإطلاق الأحكام', 'fawaid_sawtiyah_sh_albukhary_019.mp3'),
            ('نصيحة في تربية الأبناء وتأديبهم في الغرب', 'fawaid_sawtiyah_sh_albukhary_018.mp3'),
            ('كيفية معاجلة سوء الأخلاق بسبب أثر العشية في بلاد الكفر', 'fawaid_sawtiyah_sh_albukhary_017.mp3'),
            ('هل لطالب العلم أن يدعو الناس عبر وسائل التواصل الاجتماعي للاتصال به كي يفتيهم؟', 'fawaid_sawtiyah_sh_albukhary_016.mp3'),
            ('طرق معرفة الانقطاع في إسناد الحديث', 'fawaid_sawtiyah_sh_albukhary_015.mp3'),
            ('توجيهات للطلاب بمناسبة فتح معرض الكتاب', 'fawaid_sawtiyah_sh_albukhary_014.mp3'),
            ('حق الرعية على ولي الأمر', 'fawaid_sawtiyah_sh_albukhary_013.mp3'),
            ('بيان ما له حكم الرفع من أقوال الصحابة', 'fawaid_sawtiyah_sh_albukhary_012.mp3'),
            ('كيفية التعامل مع اختلاف العلماء في الجرح والتعديل', 'fawaid_sawtiyah_sh_albukhary_011.mp3'),
            ('كيفية التعامل مع الأصدقاء الذين يضيعون الوقت', 'fawaid_sawtiyah_sh_albukhary_010.mp3'),
            ('كيفية ضبط اللسان', 'fawaid_sawtiyah_sh_albukhary_009.mp3'),
            ('كيفية علاج القلب من داء الحسد', 'fawaid_sawtiyah_sh_albukhary_008.mp3'),
            ('التحذير من آراء صاحب كتاب «المنهج المقترح لفهم المصطلح»', 'fawaid_sawtiyah_sh_albukhary_007.mp3'),
            ('حكم غسل الجمعة', 'fawaid_sawtiyah_sh_albukhary_006.mp3'),
            ('تحقيق حكم جلسة الاستراحة', 'fawaid_sawtiyah_sh_albukhary_005.mp3'),
            ('التفصيل في مسألة المسافة التي يقصر فيها المسافر', 'fawaid_sawtiyah_sh_albukhary_004.mp3'),
            ('نصيحة لمن أفرط في المباحات حتى ضعفت همته في الخير', 'fawaid_sawtiyah_sh_albukhary_003.mp3'),
            ('أهمية تصحيح الأخلاق لطالب العلم', 'fawaid_sawtiyah_sh_albukhary_002.mp3'),
            ('بيان بطلان الدعوى بأن أغلب أئمة أهل السنة درسوا على أُناس مبتدعة', 'fawaid_sawtiyah_sh_albukhary_001.mp3'),
            ('وصية نافعة لطالب العلم', 'wsyah_nafeah_le_tolab_aleelm_83.mp3'),
            ('وصايا ذهبية لطلاب العلم المبتدئين', 'wsaya_zhbyah_ltlab_alelam_almbtdyn_82.mp3'),
            ('وجوب احترام علماء أهل السنة', 'wjwb_ahtram_alolmaa_81.mp3'),
            ('هلاك الناس بهلاك علمائهم', 'hlak_alnas_bhlak_alaolmah_80.mp3'),
            ('هل يمكن أن يخرج الرجل من دائرة أهل السنة بأمر واحد؟', 'hel_yhrg_alragel_men_alsonah_bamer_79.mp3'),
            ('هل يشترط النصيحة قبل التحذير؟', 'hel_yoshtrat_alnaseh_8bel_althzer_78.mp3'),
            ('هل يستحب طلب العلو  في الفتاوى الشرعية؟', 'hel_uosthab_talb_alelw_fe_alftaw_77.mp3'),
            ('هل لأكون سلفيا لا بد أن أحضر لعبيد الجابري ومحمد بن هادي وعبد الله البخاري؟', 'hal_lakwn_salfya_la_bod_an_ahder_le_albukhari_76.mp3'),
            ('هكذا عرفت الشيخ ربيعا', 'hktha_arft_alshy5_rbee_75.mp3'),
            ('نصيحة لأهل السنة الذين يعانون من إيذاء أهل البدع لهم', 'nsyeah_le_ahel_alsonah_y3anwn_men_ahel_albed3_74.mp3'),
            ('من الغلط أن تستدل بالغلط لوقوع فاضل فيه', 'mena_alghlt_an_tstdel_bel_alghlt_lw8w3_fadel_73.mp3'),
            ('مشكلة العودة إلى الذنب بعد التوبة منه', 'mshklah_alawdah_ela_althenb_72.mp3'),
            ('مخالطة أهل البدع بحجة مناصحتهم', 'm5altah_ahel_albd3_bhogah_monashtahm_71.mp3'),
            ('متى يكبر المصلي للقيام من التشهد الأول', 'mta_ykber_almosly_llgyam_mna_altshhd_70.mp3'),
            ('ليس الأصل في المسلم العدالة', 'lys_alasel_fy_almoslem_aladalah_69.mp3'),
            ('لكل مقام مقال ولكل مقال أهله', 'lekl_mkam_makal_68.mp3'),
            ('لا يقيم الحدود إلا الإمام أو نائبه', 'la_y8ym_alhdwd_ela_alemam_67.mp3'),
            ('لا يعلم الملائكة الكتبة ما في قلوب العباد', 'la_y3lm_almlakah_alktbah_ma_fy_al8lwb_66.mp3'),
            ('لا يحضرون عند المشايخ السلفيين بحجة الانشغال وعدم الوقت', 'la_yhdrwn_enda_almshay5_b7gah_alenshghal_65.mp3'),
            ('لا تلازم بين رد الخطأ وبين التبديع', 'la_tlazm_byn_rad_al5ta_wbyn_altbdy3_64.mp3'),
            ('لا تكن بوقًا للشر وسببًا في خزن علم الشيخ عنك', 'la_taken_bw8a_llshar_wsbba_fy_hazen_elem_alshy5_63.mp3'),
            ('كيفية دراسة المتون الفقهية', 'kyfyah_drasah_almtwn_alf8hyah_62.mp3'),
            ('كيفية التعامل مع السلفي إذا أخطأ', 'kyfyah_alt3aml_ma_alslfy_etha_-a5ta_61.mp3'),
            ('كيف يتأكد المسلم أنه ممسوس أو مسحور؟', 'kayf_ytakd_almoslem_anh_mmsws_60.mp3'),
            ('كلام الشيخ عبدالله البخاري في محمد الحسن ولد الددو', 'klam_alshy5_elbukhari_fy_wald_alddw_59.mp3'),
            ('قصة عجيبة في حسن خاتمة أبي زرعة الرازي', 'kosah__fy_hosn_khatmah_aby_zr3ah_alrazy_58.mp3'),
            ('فوالله إن تعلم هذه العقيدة مما يرقق القلوب ويقربها من باريها [نعمة السنة !]', 'wallh_t3lm_al38ydah_mma_yr88-alklwb_57.mp3'),
            ('طريقة الدعوة في مكان العمل', 'try8ah_aldawah_fy_mkan_alamel_56.mp3'),
            ('ضوابط الهجر الشرعي', 'dwabt_alhjer_alshar3y_55.mp3'),
            ('بطلان الاحتجاج بالمسجد النبوي على جواز الصلاة في المسجد الذي فيه قبر', 'btlan_alaehtjaj_balmsged_alnbwy_ala_fehe_aber_54.mp3'),
            ('رد الشيخ عبد الله البخاري على الأفاك المفتري عادل الكلباني في قوله داعش نبتة سلفية', 'rad_alshy5_alal_alafak_adel_alklbany_53.mp3'),
            ('دفع الإفتراء والبهتان عن الإمام محمد أمان رحمه الله', 'dfa3_df3_alftra_walbhtan_an_mohamd_algamy_52.mp3'),
            ('دفاع عن العلامة محمد أمان بن علي الجامي رحمه الله', 'dfa3_an_al3lamah_mohamd_aman_algamy_51.mp3'),
            ('حكم المشاركة في المظاهرات إذا أذن بها الحاكم', 'hokm_almsharkah_fy_almzahrat_etha_athen_beha_alhakm_50.mp3'),
            ('حكم القتال في سوريا', 'hokm_alketal_fy_Syria_49.mp3'),
            ('حكم الصور التذكارية غير المعلقة', 'hokm_alswer_altzkaryah_48.mp3'),
            ('حكم الجوالات بالكاميرا', 'hokm_algwalat_balkamyra_47.mp3'),
            ('حكم التفرغ لرقية المرضى وأخذ الأجرة عليها', 'hokm_altfrg_llrogyah_46.mp3'),
            ('حكم أخذ ما زاد عن القبضة من اللحية', 'hokm_a5z_ma_zad_an_alkabdah_45.mp3'),
            ('كلام الشيخ البخاري في عدم تسمية المخالف إذا خشي وقوع مفسدة وموافقة الشيخ ربيع له', 'tfsyl_alshy5_fy_tsmyah_almnhref_44.mp3'),
            ('تحقيق حكم جلسة الاستراحة', 't78y8_hokm_glsah_alastra7ah_43.mp3'),
            ('تبرئة الإمام الألباني من الإرجاء', 'tbrah_alalbany_mn_alrja_42.mp3'),
            ('بيان حال يحيى الحجوري والمدافعين عنه', 'byan_7al_al7gwry_walmdaf3yn_3nh_41.mp3'),
            ('بطلان الاحتجاج بالأخذ عن النووي وابن حجر على الأخذ عن المبتدعة', 'btlan_ala7tgag_bala5z_3n_alnwwy-_ala5z_almbtd3ah_40.mp3'),
            ('بطلان إخراج التحذير من أهل البدع من الجرح والتعديل', 'btlan_5rag_alt7zyr_mn_ahl_albd3_mn_algr7_39.mp3'),
            ('أهمية معرفة الصحيح والضعيف من الأحاديث', 'ahmyah_m3rfah_als7y7_wald3yf_38.mp3'),
            ('أهمية تصحيح الأخلاق', 'ahmyah_ts7y7_ala5la8_37.mp3'),
            ('الوسائل المعينة على تقوية الحفظ', 'alwsal_alm3ynah_3l_t8wyah_al7fz_36.mp3'),
            ('النصيحة لمن يقتني كتب وأشرطة أهل الأهواء والبدع', 'alnsy7ah_lmn_y8tny_ktb_ahl_alahwa_35.mp3'),
            ('النصيحة لمن يطعن في الشيخ عبيد الجابري', 'alnsy7ah_lmn_yt3n_fy_alshy5_algabry_34.mp3'),
            ('المفهوم الصحيح لتخريج الحديث', 'almfhwm_als7y7_lt5ryg_al7dyth_33.mp3'),
            ('المظاهرات في الميزان الشرعي', 'almzahrat_fy_almyzan_alshr3y_32.mp3'),
            ('الفرق بين إيقاع الهجر وبين الدعوة إليه', 'alfr8_byn_eyga3_alhagr_wbyn_ald3wah_lyh_31.mp3'),
            ('الفرق بين الحديث المرفوع والحديث القدسي', 'alfr8_byn_al7dyth_almrfw3_al8dsy_30.mp3'),
            ('الضابط في خروج الرجل من أهل السنة والجماعة', 'aldabt_fy_-wg_mn_ahl_alsnah_29.mp3'),
            ('السؤال عن أحوال الرجال', 'alsal_3n_a7wal_alrgal_28.mp3'),
            ('الرد على من يطلق لفظ المتشدد على المشايخ السلفيين', 'alrad_3l_mn_-ytl8_almtshdd_3l_almshay5_27.mp3'),
            ('الرد على من شكك في أهلية الشيخ ربيع في الجرح والتعديل', 'alrd_man_shkk_-fe_ahlayah_alshy5_rby3_fe_algr7_walt3dyl_26.mp3'),
            ('الرد على من زعم أن تقصير الثوب إلى نصف الساق من لباس الشهرة', 'alrad_man_zaam_tagser_althoobl_shohra_25.mp3'),
            ('الرد على من زعم أن باب الجرح والتعديل مغلق', 'alrad_man_zaam_ana_bab_aljarah_moglag_24.mp3'),
            ('الرد على من زعم أن المشتغلين بالجرح والتعديل غلاة', 'alrad_man_zaam_almostglin_bel_aljarah_gollat_23.mp3'),
            ('الرد على من زعم أن التحذير من أهل البدع ليس من الجرح والتعديل', 'alrad_man_zaam_altahther_laes_mena_aljarah_22.mp3'),
            ('الرد على من أنكر مشروعية الامتحان بعلماء أهل السنة', 'alrad_anker_alemthan_be_almae_alsuna_21.mp3'),
            ('الرد على من أنكر جواز جرح أهل البدع', 'alrad_man_anker_goaz_garh_ahel_albedaa_20.mp3'),
            ('الرد على من افترى أن الشيخ طعن في معاوية رضي الله عنه', 'alrad_eftara_sheikh_tann_muawiya_19.mp3'),
            ('الرد على من احتج بزيارة بعض المشايخ السلفيين لجمعية إحياء التراث', 'alrad_ehtaj_zearah_Salai_jamaah_turath_18.mp3'),
            ('الرد على شبهة التلقي عن أهل البدع وترك ما عندهم من باطل', 'alrad_-alla_chobah_altalgay_men_ahel_albedi_17.mp3'),
            ('الخلط الواقع في مسألة الهجر', 'alkhaltt_alwaq_fee_masslah_alhjaer_16.mp3'),
            ('الحكمة في تعليم الناس السنة', 'alhgmh_fee_taliem_alnas_alsunah_15.mp3'),
            ('الحزبيون لن يرضوا أحدا من العلماء', 'alhzbeon_lnn_yardaw_alalmae_14.mp3'),
            ('الجرح والتعديل مشروعيته والباعث عليه والرد على من أنكره', 'aljarh_wa_altadil_wa_alrad_13.mp3'),
            ('التميز والتمايز من أظهر خصائص السلفي', 'altamayuz_wa_altimayuz_men_adher_alsalify_12.mp3'),
            ('التلازم بين صحة الاعتقاد وصحة المنهج', 'altalazum_bain_aletiqad_wa_almanhaj_11.mp3'),
            ('التفصيل في منهج الموازنات', 'tfsel_manhj_almoisznat_10.mp3'),
            ('التعليق على قول الإمام أحمد في تحريم الخروج على الائمة', 'thareem_-khruoj_ahmed_9.mp3'),
            ('التدرج في طلب العلم والتلقي على أيدي المشايخ سنة متبعة', 'tadrj_taelb_aleam_08.mp3'),
            ('التحذير من مسلسل الفاروق عمر بن الخطاب', 'thzear_muslsel_alFaruq_07.mp3'),
            ('التحذير من فريد بن جمعة زمور الجزائري', 'thzear_freed_bin_Juma_06.mp3'),
            ('التحذير من الكذب', 'althezer_menah_alkzeb_05.mp3'),
            ('التحذير من استغلال أهل الأهواء الإجازات لصيد الشباب السني', 'alththeer_estglal_ahel_alhoa_-alejazzat_04.mp3'),
            ('الاعتناء بفهم السلف للنصوص', 'alatnia_pfhm_alssilf_nsos_03.mp3'),
            ('إساءة الأدب مع الشيخ سبب الحرمان من علمه', 'esah_aladb_mah_alchek_02.mp3'),
            ('أدب السؤال', 'Adb-Alsoal.mp3'),
        ]




        self.add_audios(audios=qa, ModelName=QATrack)
